[pytest]
addopts = -p no:django -p no:langsmith -p no:logfire -p no:cov -W ignore::DeprecationWarning
asyncio_mode = strict
asyncio_default_fixture_loop_scope = function
testpaths = tests
norecursedirs = scratch .venv build dist
